apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: orders
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: payments
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: users
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
