AWSTemplateFormatVersion: "2010-09-09"
Description: "Module NAT Gateway cho Private Subnet"

Parameters:
  VpcId:
    Type: String
  PublicSubnetId:
    Type: String

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnetId
      AllocationId: !GetAtt EIP.AllocationId

Outputs:
  NatGatewayId:
    Value: !Ref NatGateway
