apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices
commonLabels:
  app.kubernetes.io/part-of: microservices-stack
resources:
  - orders-deployment.yaml
  - orders-service.yaml
  - payments-deployment.yaml
  - payments-service.yaml
  - users-deployment.yaml
  - users-service.yaml
