apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: payments
  type: ClusterIP
